export enum OrderStatusEnum {
  IN_ANALISIS = 'IN_ANALISIS',
  IN_PREPATION = 'IN_PREPATION',
  WAITING_FOR_WITHDRAWL = 'WAITING_FOR_WITHDRAWL',
  SENT = 'SENT',
  DONE = 'DONE',
  CANCELED = 'CANCELED',
}
